apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hfm09tu9x-python 
  janus-idp.io/tekton: hfm09tu9x-python
  backstage.io/kubernetes-id: hfm09tu9x-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hfm09tu9x-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml