apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hfm09tu9x-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hfm09tu9x-python 
  name: hfm09tu9x-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hfm09tu9x-python 
