apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hfm09tu9x-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-2f87bafb37.8d0i.p3.openshiftapps.com/rhtap/rhtap-qe-python:7311d128b893a16b16c8578985c825225f0599f8@sha256:3621654ce1ece3552db6d59347af5f244ff2a6bd3df7a913d43ef4eac6e4d77a
          name: container-image
